### ISSUE TITLE
ln: failed to create symbolic link

### ISSUE THREAD

**Issue by Kennjo** [ctu-mrs/leader_follower_task#1]
I get an  error that says symbolic link fails to create when running 'ln -s ~/git/leader_follower_task/ros_packages/*' in my workspace. Any advice on how to solve this 
![Screenshot from 2021-05-05 14-46-35](https://user-images.githubusercontent.com/82135832/117105753-439b4d00-adb1-11eb-99a9-e7b25c451df2.png)
`ekiost@ekiost:~/mrs_workspace/src$ ln -s ~/git/leader_follower_task/ros_packages/*
ln: failed to create symbolic link '/home/ekiost/git/leader_follower_task/ros_packages/uvdar_leader_follower/summer_school_supervisor': File exists
ln: failed to create symbolic link '/home/ekiost/git/leader_follower_task/ros_packages/uvdar_leader_follower/trajectory_loader': File exists
ln: failed to create symbolic link '/home/ekiost/git/leader_follower_task/ros_packages/uvdar_leader_follower/uvdar_core': File exists
ln: failed to create symbolic link '/home/ekiost/git/leader_follower_task/ros_packages/uvdar_leader_follower/uvdar_gazebo_plugin': File exists
`

**Comment by spurnvoj** [comment]
Hi, this only means that links already exist (You have called this command before). This is not an error, but to not mislead the user, I added force linking. So the command will be successful every time. See https://github.com/ctu-mrs/leader_follower_task/commit/f354062bcc03be538b0eb329a8ee5247e9502c84. Thanks

**Comment by Kennjo** [comment]
> Hi, this only means that links already exist (You have called this command before). This is not an error, but to not mislead the user, I added force linking. So the command will be successful every time. See [f354062](https://github.com/ctu-mrs/leader_follower_task/commit/f354062bcc03be538b0eb329a8ee5247e9502c84). Thanks

Thanks for clarifying, I couldn't find the folder of the simulation "tmux_scripts/two_drones_uvdar" after running "ln -s ~/git/leader_follower_task/ros_packages/*" in my workspace so I had assume that was the issue. 

Even after rebuilding the workspace and reinstalling leader_follower_task I still can't access the the two_drones_uvdar folder. 
Am I missing a step or doing something wrong?
Again, thanks for your help and clarification

**Comment by spurnvoj** [comment]
The command for linking repositories was missing a dot at the end.
```bash
ln -sf ~/git/leader_follower_task/ros_packages/* .
```
Readme should be fixed now. Please try it again :)

**Comment by Kennjo** [comment]
> The command for linking repositories was missing a dot at the end.
> 
> ```shell
> ln -sf ~/git/leader_follower_task/ros_packages/* .
> ```
> 
> Readme should be fixed now. Please try it again :)

I got it working now, but I believe the space between the "*" and "." needs to be removed. Thanks so much for you help once again. I will close this issue now.

**Comment by kielerrr** [comment]
> I got it working now, but I believe the space between the "*" and "." needs to be removed. Thanks so much for your help once again. I will close this issue now.

How were you able to get it working? The file `two_drones_uvdar` doesn't seem to exist in the repo or anywhere in the ctu-mrs organization.
