### ISSUE TITLE
Gazebo's drone not spawning

### ISSUE THREAD

**Issue by ZhiWei20011** [ctu-mrs/leader_follower_task#5]
Hi, my gazebo is not able to spawn the two drones when I'm running the uvdar_leader_follower /tmux_scripts/simulation_two_drones program. In addition, the Rviz program will also not launch. Thank you in advance!
![Screenshot from 2021-06-16 00-36-06](https://user-images.githubusercontent.com/85549044/122021344-2ae27600-cdf8-11eb-8896-52c7aa1887d8.png)
![Screenshot from 2021-06-16 00-36-06](https://user-images.githubusercontent.com/85549044/122021464-4483bd80-cdf8-11eb-8ca7-675586bf63f1.png)

**Comment by bednarhonza** [comment]
Hello,
I cannot see the errors you have in the provided screenshots. Please, go through the terminal tmux sessions, and screenshot the errors there. The current window, go to start, is not essential for drone spawning.

Thank you,
Jan

**Comment by stibipet** [comment]
Hey, it looks like you are using the newest version of **simulation**, but this task is not yet compatible with it. There were some changes in sensor naming the respective spawning mechanism, which haven't been pushed into this repo yet.

You can manually checkout to an older commit of simulation by navigating to the **simulation** folder and calling
`git checkout 756dfa0e60eef0e92486496e8615d9801c8690b7`

Afterwards, you will need to compile the workspace containing simulation (by calling `catkin build`) and try to run the tmux script again.

Petr

**Comment by ZhiWei20011** [comment]
Hi, I am able to spawn those two drones after reinstalling and doing git checkout 756dfa0e60eef0e92486496e8615d9801c8690b7. Thank you.
